name: xpublish
channels:
  - conda-forge
dependencies:
  - python=3
  - xarray
  - netcdf4
  - zarr
  - numcodecs
  - fastapi
  - uvicorn
  - fsspec
  - dask
  - distributed
  - cachey
  - dask-labextension
  - jupyter-server-proxy
  - toolz
  - bokeh
  - ipytree
  - pip
  - pooch
