name: Build Python distribution and upload to PyPI on release

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  deploy:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade build

      - name: Build binary wheel
        run: python -m build --sdist --wheel . --outdir dist

      - name: Check files
        run: >
          ls dist
          && python -m pip install --upgrade check-manifest
          && check-manifest --verbose

      - name: Test wheels
        run: >
          cd dist
          && python -m pip install *.whl
          && python -m pip install --upgrade build twine
          && python -m twine check *

      - name: Publish a Python distribution to PyPI
        if: success() && github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
